// AI-Q site data — full bilingual content from the original site

const I18N = {
  nav: {
    framework: { en: 'The Framework', es: 'El Framework' },
    types:     { en: 'The 16 Types',  es: 'Los 16 Tipos' },
    sama:      { en: 'SAMA',          es: 'SAMA' },
    cases:     { en: 'Case Studies',  es: 'Casos de Estudio' },
    cta:       { en: 'Take the Test', es: 'Hacer el Test' },
  },
  hero: {
    eyebrow:  { en: 'The A.I. Strategy Type Indicator',
                es: 'El Indicador de Tipo de Estrategia I.A.' },
    h1Small:  { en: "What's your", es: '¿Cuál es tu' },
    h1Mark:   { en: '?', es: '?' },
    quote: {
      en: 'Like Myers-Briggs measures personality, A.I.-Q measures your organization\u2019s strategy across four dimensions and reveals which of sixteen types you are.',
      es: 'Como Myers-Briggs mide la personalidad, A.I.-Q mide la estrategia de tu organizaci\u00f3n en cuatro dimensiones y revela cu\u00e1l de los diecis\u00e9is tipos eres.',
    },
    lead: {
      en: 'Most companies think they have an A.I. strategy. They have, at best, a collection of tools. This twenty-question diagnostic reveals the truth \u2014 and shows you how to fix it.',
      es: 'La mayor\u00eda de las empresas creen que tienen una estrategia de I.A. Tienen, en el mejor de los casos, una colecci\u00f3n de herramientas. Este diagn\u00f3stico de veinte preguntas revela la verdad \u2014 y te muestra c\u00f3mo solucionarlo.',
    },
    primary:   { en: 'Discover Your Type',  es: 'Descubre tu Tipo' },
    secondary: { en: 'Explore the Sixteen Types', es: 'Explorar los Diecis\u00e9is Tipos' },
    s1n:'16', s1l:{ en:'Distinct Types', es:'Tipos Distintos' },
    s2n:'20', s2l:{ en:'Questions',      es:'Preguntas' },
    s3n:'4',  s3l:{ en:'Dimensions',     es:'Dimensiones' },
  },
  dim: {
    eyebrow: { en:'The Framework', es:'El Framework' },
    title:   { en:'Four Dimensions of A.I. Maturity',
               es:'Cuatro Dimensiones de Madurez en I.A.' },
    lead: {
      en:'Like Myers-Briggs measures personality, A.I.-Q measures your organization\u2019s A.I. strategy across four critical dimensions.',
      es:'Como Myers-Briggs mide la personalidad, A.I.-Q mide la estrategia de I.A. de tu organizaci\u00f3n en cuatro dimensiones cr\u00edticas.',
    },
  },
  types: {
    eyebrow: { en:'The 16 Types', es:'Los 16 Tipos' },
    title:   { en:'Which One Are You?', es:'\u00bfCu\u00e1l Eres T\u00fa?' },
    lead: {
      en:'Each type has strengths and blind spots. The goal isn\u2019t to judge \u2014 it\u2019s to see clearly and move forward.',
      es:'Cada tipo tiene fortalezas y puntos ciegos. El objetivo no es juzgar \u2014 es ver claramente y avanzar.',
    },
    chips: {
      all:          { en:'All Types',     es:'Todos los Tipos' },
      scattered:    { en:'Scattered (S)', es:'Disperso (S)' },
      consolidated: { en:'Consolidated (C)', es:'Consolidado (C)' },
    },
  },
  cases: {
    eyebrow: { en:'Case Studies', es:'Casos de Estudio' },
    title:   { en:'Learn from Real Cases', es:'Aprende de Casos Reales' },
    lead: {
      en:'See how major enterprises map to A.I.-Q types \u2014 and what separates the 5% that succeed from the 95% that don\u2019t.',
      es:'Mir\u00e1 c\u00f3mo las grandes empresas se mapean a los tipos de A.I.-Q \u2014 y qu\u00e9 separa al 5% que tiene \u00e9xito del 95% que no.',
    },
    enTitle: { en:'Enterprise A.I. Case Studies', es:'Casos de I.A. Empresarial (English)' },
    enDesc:  { en:'JPMorgan, DBS Bank, Walmart, McDonald\u2019s, Zillow \u2014 mapped to A.I.-Q archetypes with sources.',
               es:'JPMorgan, DBS Bank, Walmart, McDonald\u2019s, Zillow \u2014 mapeados a arquetipos A.I.-Q con fuentes.' },
    esTitle: { en:'Enterprise Case Studies (Spanish)', es:'Casos de I.A. Empresarial' },
    esDesc:  { en:'Mismo dossier, en espa\u00f1ol. JPMorgan, DBS Bank, Walmart, McDonald\u2019s, Zillow.',
               es:'JPMorgan, DBS Bank, Walmart, McDonald\u2019s, Zillow \u2014 mapeados a arquetipos A.I.-Q con fuentes.' },
    guideTitle:{ en:'A.I.-Q Types Guide', es:'Gu\u00eda de Tipos A.I.-Q' },
    guideDesc: { en:'Field guide to all sixteen archetypes \u2014 strengths, blind-spots, and a path forward.',
                 es:'Gu\u00eda completa de los diecis\u00e9is arquetipos \u2014 fortalezas, puntos ciegos y camino a seguir.' },
    citation: {
      en:'Based on McKinsey, MIT Project NANDA, Deloitte & company reports (2024-2025).',
      es:'Basado en McKinsey, MIT Project NANDA, Deloitte e informes de empresas (2024-2025).',
    },
    download: { en:'Download PDF', es:'Descargar PDF' },
  },
  cta: {
    eyebrow:{ en:'Five Minutes \u00b7 Free \u00b7 Blunt', es:'Cinco Minutos \u00b7 Gratis \u00b7 Directo' },
    title:  { en:'Ready to discover your type?', es:'\u00bfListo para descubrir tu tipo?' },
    lead:   { en:'Twenty questions. Five minutes. Complete clarity on where you stand and what to do next.',
              es:'Veinte preguntas. Cinco minutos. Claridad completa sobre d\u00f3nde est\u00e1s y qu\u00e9 hacer despu\u00e9s.' },
    primary:{ en:'Begin the Assessment', es:'Comenzar la Evaluaci\u00f3n' },
    secondary:{ en:'Download the Complete Guide (PDF)', es:'Descargar la Gu\u00eda Completa (PDF)' },
  },
  foot: {
    tag: { en:'The A.I. Strategy Type Indicator by Dr. Federico Andino.',
           es:'El Indicador de Tipo de Estrategia de I.A. del Dr. Federico Andino.' },
    framework:{ en:'Framework', es:'Framework' },
    types:    { en:'Types',     es:'Tipos' },
    author:   { en:'About the Author', es:'Sobre el Autor' },
    copy:     { en:'\u00a9 MMXXV \u00b7 Andino & Co. \u00b7 All rights reserved.',
                es:'\u00a9 MMXXV \u00b7 Andino & Co. \u00b7 Todos los derechos reservados.' },
  },
  modal: {
    profile:    { en:'Profile',          es:'Perfil' },
    strengths:  { en:'Strengths',        es:'Fortalezas' },
    blindspots: { en:'Blind Spots',      es:'Puntos Ciegos' },
    symptoms:   { en:'Typical Symptoms', es:'S\u00edntomas T\u00edpicos' },
    path:       { en:'Path Forward',     es:'Camino a Seguir' },
    fullGuide:  { en:'See Full Guide',   es:'Ver Gu\u00eda Completa' },
  },
};

const DIMENSIONS = [
  { key:'S', title:{en:'Structure',es:'Estructura'},
    left:{en:'Scattered',es:'Disperso'}, right:{en:'Consolidated',es:'Consolidado'},
    desc:{en:'How organized is your A.I. landscape? Random tools bought by different teams, or a unified, governed ecosystem?',
          es:'\u00bfQu\u00e9 tan organizado est\u00e1 tu panorama de I.A.? \u00bfHerramientas aleatorias compradas por diferentes equipos, o un ecosistema unificado y gobernado?'} },
  { key:'O', title:{en:'Orientation',es:'Orientaci\u00f3n'},
    left:{en:'Reactive',es:'Reactivo'}, right:{en:'Proactive',es:'Proactivo'},
    desc:{en:'Do you chase A.I. trends and respond to pressure, or anticipate needs and plan strategically ahead?',
          es:'\u00bfPersigues tendencias de I.A. y respondes a la presi\u00f3n, o anticipas necesidades y planificas estrat\u00e9gicamente?'} },
  { key:'L', title:{en:'Leadership',es:'Liderazgo'},
    left:{en:'Tech-driven',es:'Tech-driven'}, right:{en:'Business-driven',es:'Business-driven'},
    desc:{en:'Who owns A.I. decisions? IT building capabilities, or business leaders driving outcomes?',
          es:'\u00bfQui\u00e9n toma las decisiones de I.A.? \u00bfIT construyendo capacidades, o l\u00edderes de negocio impulsando resultados?'} },
  { key:'I', title:{en:'Integration',es:'Integraci\u00f3n'},
    left:{en:'Experimental',es:'Experimental'}, right:{en:'Integrated',es:'Integrado'},
    desc:{en:'Are A.I. tools siloed experiments and pilots, or deeply embedded in daily workflows?',
          es:'\u00bfLas herramientas de I.A. son experimentos aislados y pilotos, o est\u00e1n profundamente integradas en los flujos de trabajo diarios?'} },
];

// Full 16 types — bilingual content sourced from index.html
const TYPES = [
{code:"SRTE",name:{en:"The Chaos Pilot",es:"El Piloto del Caos"},tagline:{en:"We have AI... somewhere.",es:"Tenemos IA... en algún lugar."},quadrant:"Scattered",
 description:{en:"Your A.I. landscape is a graveyard of good intentions. Multiple tools bought by different teams, none talking to each other, no clear owner, no measurable outcomes.",
              es:"Tu panorama de I.A. es un cementerio de buenas intenciones. M\u00faltiples herramientas compradas por diferentes equipos, ninguna se comunica con otra, sin due\u00f1o claro, sin resultados medibles."},
 strengths:{en:["Willingness to try new things","Budget available for A.I.","No legacy system lock-in"],
            es:["Disposici\u00f3n para probar cosas nuevas","Presupuesto disponible para I.A.","Sin dependencia de sistemas legacy"]},
 blindspots:{en:["No idea what you're actually spending","Can't measure ROI","Teams are frustrated"],
             es:["Sin idea de lo que realmente gastas","No puedes medir ROI","Los equipos est\u00e1n frustrados"]},
 symptoms:{en:["We have Copilot, ChatGPT Enterprise, and three other tools","I think marketing bought something last month","Our A.I. strategy is... we use A.I."],
           es:["Tenemos Copilot, ChatGPT Enterprise y tres herramientas m\u00e1s","Creo que marketing compr\u00f3 algo el mes pasado","Nuestra estrategia de I.A. es... usamos I.A."]},
 path:{en:"Stop buying. Start auditing. You need a complete inventory before anything else.",
       es:"Deja de comprar. Comienza a auditar. Necesitas un inventario completo antes que nada."}},
{code:"SRTB",name:{en:"The Wishful Thinker",es:"El Pensador Idealista"},tagline:{en:"Can't AI just do that?",es:"\u00bfNo puede la IA simplemente hacer eso?"},quadrant:"Scattered",
 description:{en:"Leadership is excited about A.I. but treats it like magic. Requests come down like 'use A.I. to fix customer churn' with no specifics.",
              es:"El liderazgo est\u00e1 entusiasmado con la I.A. pero la trata como magia. Las solicitudes llegan como 'usa I.A. para arreglar la p\u00e9rdida de clientes' sin especificaciones."},
 strengths:{en:["Executive attention on A.I.","Business problems are the focus","Budget unlocks possible"],
            es:["Atenci\u00f3n ejecutiva en I.A.","Los problemas de negocio son el foco","Desbloqueo de presupuesto posible"]},
 blindspots:{en:["Unrealistic expectations","No technical translation layer","Initiatives die from vagueness"],
             es:["Expectativas poco realistas","Sin capa de traducci\u00f3n t\u00e9cnica","Las iniciativas mueren por vaguedad"]},
 symptoms:{en:["The CEO read an article and now we need an A.I. strategy by Friday","Can we use ChatGPT to predict which customers will leave?","Why isn't this working yet?"],
           es:["El CEO ley\u00f3 un art\u00edculo y ahora necesitamos una estrategia de I.A. para el viernes","\u00bfPodemos usar ChatGPT para predecir qu\u00e9 clientes se ir\u00e1n?","\u00bfPor qu\u00e9 esto a\u00fan no funciona?"]},
 path:{en:"Translate business wishes into specific, measurable problems.",
       es:"Traduce los deseos del negocio en problemas espec\u00edficos y medibles."}},
{code:"SPTE",name:{en:"The Over-Engineer",es:"El Sobre-Ingeniero"},tagline:{en:"The architecture is beautiful. Nobody uses it.",es:"La arquitectura es hermosa. Nadie la usa."},quadrant:"Scattered",
 description:{en:"Your tech team built impressive A.I. infrastructure. One problem: business users don't know it exists.",
              es:"Tu equipo t\u00e9cnico construy\u00f3 una impresionante infraestructura de I.A. Un problema: los usuarios de negocio no saben que existe."},
 strengths:{en:["Strong technical capability","Forward-thinking IT","Modern infrastructure"],
            es:["Fuerte capacidad t\u00e9cnica","IT con visi\u00f3n de futuro","Infraestructura moderna"]},
 blindspots:{en:["Disconnect from business reality","Build it and they'll come mentality","Measuring wrong metrics"],
             es:["Desconexi\u00f3n de la realidad del negocio","Mentalidad de 'constr\u00fayelo y vendr\u00e1n'","Midiendo m\u00e9tricas incorrectas"]},
 symptoms:{en:["We have a world-class ML platform that three people use","The data team built an amazing model but ops won't adopt it","We're ready for A.I. \u2014 we just need use cases"],
           es:["Tenemos una plataforma ML de clase mundial que usan tres personas","El equipo de datos construy\u00f3 un modelo incre\u00edble pero ops no lo adopta","Estamos listos para I.A. \u2014 solo necesitamos casos de uso"]},
 path:{en:"Stop building. Start listening. Find real problems worth solving.",
       es:"Deja de construir. Comienza a escuchar. Encuentra problemas reales que valga la pena resolver."}},
{code:"SPTB",name:{en:"The Ambitious Starter",es:"El Iniciador Ambicioso"},tagline:{en:"Great strategy, scattered execution.",es:"Gran estrategia, ejecuci\u00f3n dispersa."},quadrant:"Scattered",
 description:{en:"Good intentions, executive buy-in, strategy on paper. But execution is chaos.",
              es:"Buenas intenciones, apoyo ejecutivo, estrategia en papel. Pero la ejecuci\u00f3n es caos."},
 strengths:{en:["Executive sponsorship","Strategic thinking","Business-driven priorities"],
            es:["Patrocinio ejecutivo","Pensamiento estrat\u00e9gico","Prioridades impulsadas por el negocio"]},
 blindspots:{en:["Too many priorities","Lacks coordination","Strategy diverging from reality"],
             es:["Demasiadas prioridades","Falta coordinaci\u00f3n","Estrategia divergiendo de la realidad"]},
 symptoms:{en:["We have a strategy deck but every team is doing their own thing","The vision is clear, the roadmap is... flexible","We're aligned on the 'what' but not the 'how'"],
           es:["Tenemos un deck de estrategia pero cada equipo hace lo suyo","La visi\u00f3n es clara, el roadmap es... flexible","Estamos alineados en el 'qu\u00e9' pero no en el 'c\u00f3mo'"]},
 path:{en:"Pick THREE initiatives maximum. Kill everything else.",
       es:"Elige TRES iniciativas m\u00e1ximo. Elimina todo lo dem\u00e1s."}},
{code:"SRTI",name:{en:"The Accidental Success",es:"El \u00c9xito Accidental"},tagline:{en:"It works, but don't ask me how.",es:"Funciona, pero no me preguntes c\u00f3mo."},quadrant:"Scattered",
 description:{en:"Against all odds, you have A.I. integrated into workflows. But it happened by accident.",
              es:"Contra todo pron\u00f3stico, tienes I.A. integrada en los flujos de trabajo. Pero sucedi\u00f3 por accidente."},
 strengths:{en:["Proof A.I. can work here","A champion exists","Real value being created"],
            es:["Prueba de que la I.A. puede funcionar aqu\u00ed","Existe un campe\u00f3n","Se est\u00e1 creando valor real"]},
 blindspots:{en:["Single point of failure","Not replicable","Leadership unaware"],
             es:["Punto \u00fanico de falla","No replicable","Liderazgo no consciente"]},
 symptoms:{en:["Sarah in ops built this amazing automation","I don't know how the model works, but it's been accurate","We should probably document this someday"],
           es:["Sarah en operaciones construy\u00f3 esta automatizaci\u00f3n incre\u00edble","No s\u00e9 c\u00f3mo funciona el modelo, pero ha sido preciso","Probablemente deber\u00edamos documentar esto alg\u00fan d\u00eda"]},
 path:{en:"Document everything. Now. Turn accidental wins into repeatable processes.",
       es:"Documenta todo. Ahora. Convierte los \u00e9xitos accidentales en procesos repetibles."}},
{code:"SRBI",name:{en:"The Shadow IT Hero",es:"El H\u00e9roe de Shadow IT"},tagline:{en:"Don't tell IT, but this is working.",es:"No le digas a IT, pero esto est\u00e1 funcionando."},quadrant:"Scattered",
 description:{en:"Business users signed up for A.I. tools with credit cards and are getting results. IT doesn't know.",
              es:"Los usuarios de negocio se registraron en herramientas de I.A. con tarjetas de cr\u00e9dito y est\u00e1n obteniendo resultados. IT no lo sabe."},
 strengths:{en:["Bias toward action","Real problems solved","Proof of demand"],
            es:["Sesgo hacia la acci\u00f3n","Problemas reales resueltos","Prueba de demanda"]},
 blindspots:{en:["Security/compliance risks","No scalability path","Data silos"],
             es:["Riesgos de seguridad/cumplimiento","Sin camino de escalabilidad","Silos de datos"]},
 symptoms:{en:["My team uses Claude but don't tell anyone","We expensed it as 'software subscriptions'","IT would take six months to approve this"],
           es:["Mi equipo usa Claude pero no le digas a nadie","Lo pasamos como 'suscripciones de software'","IT tardar\u00eda seis meses en aprobar esto"]},
 path:{en:"Bring it into the light. Partner with IT to legitimize what's working.",
       es:"S\u00e1calo a la luz. As\u00f3ciate con IT para legitimar lo que funciona."}},
{code:"SPTI",name:{en:"The Rogue Lab",es:"El Laboratorio Rebelde"},tagline:{en:"Our tech is amazing. The business doesn't care.",es:"Nuestra tecnolog\u00eda es incre\u00edble. Al negocio no le importa."},quadrant:"Scattered",
 description:{en:"Proactive tech team with integrated A.I. But what they build has little connection to business priorities.",
              es:"Equipo t\u00e9cnico proactivo con I.A. integrada. Pero lo que construyen tiene poca conexi\u00f3n con las prioridades del negocio."},
 strengths:{en:["Technical excellence","Innovation culture","Integrated infrastructure"],
            es:["Excelencia t\u00e9cnica","Cultura de innovaci\u00f3n","Infraestructura integrada"]},
 blindspots:{en:["Building for engineers","Seen as cost center","No strategy seat"],
             es:["Construyendo para ingenieros","Vistos como centro de costos","Sin asiento en la estrategia"]},
 symptoms:{en:["We could do so much more if business understood A.I.","They asked for a chatbot when they need a knowledge graph","We're three years ahead of where the company wants to be"],
           es:["Podr\u00edamos hacer mucho m\u00e1s si el negocio entendiera I.A.","Pidieron un chatbot cuando necesitan un knowledge graph","Estamos tres a\u00f1os adelante de donde la empresa quiere estar"]},
 path:{en:"Translate capabilities into business language. Find one executive sponsor.",
       es:"Traduce las capacidades al lenguaje del negocio. Encuentra un patrocinador ejecutivo."}},
{code:"SPBI",name:{en:"The Grassroots Movement",es:"El Movimiento de Base"},tagline:{en:"Pockets of excellence, waiting to connect.",es:"Bolsillos de excelencia, esperando conectarse."},quadrant:"Scattered",
 description:{en:"Multiple departments doing A.I. well. But they're not talking to each other.",
              es:"M\u00faltiples departamentos haciendo bien la I.A. Pero no se comunican entre s\u00ed."},
 strengths:{en:["Proven success across teams","Business ownership","High adoption in pockets"],
            es:["\u00c9xito probado en varios equipos","Propiedad del negocio","Alta adopci\u00f3n en bolsillos"]},
 blindspots:{en:["Duplicated effort","Incompatible tools","No enterprise view"],
             es:["Esfuerzo duplicado","Herramientas incompatibles","Sin visi\u00f3n empresarial"]},
 symptoms:{en:["Every department has their own A.I. thing going","We should probably compare notes sometime","Wait, you're using the same vendor?"],
           es:["Cada departamento tiene su propia cosa de I.A.","Probablemente deber\u00edamos comparar notas alg\u00fan d\u00eda","Espera, \u00bfustedes usan el mismo proveedor?"]},
 path:{en:"Create a coordination layer \u2014 not to control, but to connect.",
       es:"Crea una capa de coordinaci\u00f3n \u2014 no para controlar, sino para conectar."}},
{code:"CRTE",name:{en:"The Controlled Experiment",es:"El Experimento Controlado"},tagline:{en:"We're piloting... still.",es:"Estamos piloteando... todav\u00eda."},quadrant:"Consolidated",
 description:{en:"Consolidated A.I. tools with good governance. But stuck in permanent pilot mode.",
              es:"Herramientas de I.A. consolidadas con buena gobernanza. Pero atascados en modo piloto permanente."},
 strengths:{en:["Low risk","Clean tool landscape","Good governance"],
            es:["Bajo riesgo","Panorama de herramientas limpio","Buena gobernanza"]},
 blindspots:{en:["Pilots never become products","Business losing patience","Vague success metrics"],
             es:["Los pilotos nunca se convierten en productos","El negocio pierde la paciencia","M\u00e9tricas de \u00e9xito vagas"]},
 symptoms:{en:["We've been piloting this for 18 months","It works in the test environment","We need more data before we can scale"],
           es:["Hemos estado piloteando esto por 18 meses","Funciona en el ambiente de pruebas","Necesitamos m\u00e1s datos antes de escalar"]},
 path:{en:"Set a kill date for every pilot. Graduate to production or shut it down.",
       es:"Establece una fecha l\u00edmite para cada piloto. Grad\u00faa a producci\u00f3n o ci\u00e9rralo."}},
{code:"CRTB",name:{en:"The Waiting Game",es:"El Juego de la Espera"},tagline:{en:"We're ready to be ready.",es:"Estamos listos para estar listos."},quadrant:"Consolidated",
 description:{en:"Business owns A.I. decisions, consolidated tools, but everything is reactive and cautious.",
              es:"El negocio es due\u00f1o de las decisiones de I.A., herramientas consolidadas, pero todo es reactivo y cauteloso."},
 strengths:{en:["Clean landscape","Business alignment","No expensive mistakes"],
            es:["Panorama limpio","Alineaci\u00f3n del negocio","Sin errores costosos"]},
 blindspots:{en:["Competitors are moving","Right time never comes","Talent is bored"],
             es:["Los competidores se est\u00e1n moviendo","El momento correcto nunca llega","El talento est\u00e1 aburrido"]},
 symptoms:{en:["We're monitoring A.I. trends closely","We want to be fast followers","Once the hype settles, we'll make our move"],
           es:["Estamos monitoreando las tendencias de I.A. de cerca","Queremos ser seguidores r\u00e1pidos","Una vez que el hype se calme, haremos nuestro movimiento"]},
 path:{en:"Pick one low-risk, high-visibility initiative. Get in the game.",
       es:"Elige una iniciativa de bajo riesgo y alta visibilidad. Entra al juego."}},
{code:"CPTE",name:{en:"The Tech Utopia",es:"La Utop\u00eda Tecnol\u00f3gica"},tagline:{en:"If only people would use what we built.",es:"Si tan solo la gente usara lo que construimos."},quadrant:"Consolidated",
 description:{en:"You've done everything right \u2014 technically. The only thing missing: people using it.",
              es:"Has hecho todo bien \u2014 t\u00e9cnicamente. Lo \u00fanico que falta: gente us\u00e1ndolo."},
 strengths:{en:["Solid technical foundation","Future-proof architecture","Ready to scale"],
            es:["Base t\u00e9cnica s\u00f3lida","Arquitectura a prueba de futuro","Listo para escalar"]},
 blindspots:{en:["Adoption is THE problem","Change management skipped","Technical elegance \u2260 value"],
             es:["La adopci\u00f3n ES el problema","Se saltaron la gesti\u00f3n del cambio","Elegancia t\u00e9cnica \u2260 valor"]},
 symptoms:{en:["The platform is ready \u2014 we just need people to use it","We built exactly what they asked for (but they're not using it)","Training should solve the adoption problem"],
           es:["La plataforma est\u00e1 lista \u2014 solo necesitamos que la gente la use","Construimos exactamente lo que pidieron (pero no lo usan)","El entrenamiento deber\u00eda resolver el problema de adopci\u00f3n"]},
 path:{en:"Stop building features. Start building relationships.",
       es:"Deja de construir funcionalidades. Comienza a construir relaciones."}},
{code:"CPTB",name:{en:"The Strategy Doc",es:"El Documento de Estrategia"},tagline:{en:"The deck is ready. Execution isn't.",es:"El deck est\u00e1 listo. La ejecuci\u00f3n no."},quadrant:"Consolidated",
 description:{en:"Beautiful strategy, executive alignment. But stuck between strategy and execution.",
              es:"Hermosa estrategia, alineaci\u00f3n ejecutiva. Pero atascados entre estrategia y ejecuci\u00f3n."},
 strengths:{en:["Clear vision","Stakeholder buy-in","Prioritized roadmap"],
            es:["Visi\u00f3n clara","Apoyo de stakeholders","Roadmap priorizado"]},
 blindspots:{en:["Perfectionism as planning","Waiting for ideal conditions","Strategy getting stale"],
             es:["Perfeccionismo como planificaci\u00f3n","Esperando condiciones ideales","La estrategia se vuelve obsoleta"]},
 symptoms:{en:["We're finalizing the implementation plan","Once we hire the right person, we'll start","The strategy is solid \u2014 execution is the next phase"],
           es:["Estamos finalizando el plan de implementaci\u00f3n","Una vez que contratemos a la persona correcta, comenzaremos","La estrategia es s\u00f3lida \u2014 la ejecuci\u00f3n es la siguiente fase"]},
 path:{en:"Pick ONE initiative. Start THIS WEEK. Imperfect action beats perfect planning.",
       es:"Elige UNA iniciativa. Comienza ESTA SEMANA. La acci\u00f3n imperfecta supera la planificaci\u00f3n perfecta."}},
{code:"CRTI",name:{en:"The Efficient Machine",es:"La M\u00e1quina Eficiente"},tagline:{en:"Responsive but not innovative.",es:"Responsivo pero no innovador."},quadrant:"Consolidated",
 description:{en:"IT runs a tight ship responding to requests. But optimizing yesterday's operations.",
              es:"IT maneja un barco ajustado respondiendo a solicitudes. Pero optimizando las operaciones de ayer."},
 strengths:{en:["Reliable execution","Strong governance","Efficient operations"],
            es:["Ejecuci\u00f3n confiable","Gobernanza fuerte","Operaciones eficientes"]},
 blindspots:{en:["No innovation pipeline","Reactive means behind","IT seen as utility"],
             es:["Sin pipeline de innovaci\u00f3n","Reactivo significa atrasado","IT visto como utilidad"]},
 symptoms:{en:["We deliver what the business asks for","Our SLAs are excellent","Innovation isn't really our mandate"],
           es:["Entregamos lo que el negocio pide","Nuestros SLAs son excelentes","La innovaci\u00f3n realmente no es nuestro mandato"]},
 path:{en:"Carve out 20% for proactive exploration.",
       es:"Reserva 20% para exploraci\u00f3n proactiva."}},
{code:"CRBI",name:{en:"The Service Desk",es:"El Service Desk"},tagline:{en:"We deliver what you ask for \u2014 nothing more.",es:"Entregamos lo que pides \u2014 nada m\u00e1s."},quadrant:"Consolidated",
 description:{en:"A.I. is integrated and business-driven, but entirely reactive.",
              es:"La I.A. est\u00e1 integrada y es impulsada por el negocio, pero es completamente reactiva."},
 strengths:{en:["Reliable execution","Business trust","Working integrations"],
            es:["Ejecuci\u00f3n confiable","Confianza del negocio","Integraciones funcionando"]},
 blindspots:{en:["Missing opportunities","A.I. as cost center","No proactive roadmap"],
             es:["Perdiendo oportunidades","I.A. como centro de costos","Sin roadmap proactivo"]},
 symptoms:{en:["We're here to support business initiatives","When they bring us requirements, we deliver","Strategy isn't our job \u2014 we're execution"],
           es:["Estamos aqu\u00ed para apoyar las iniciativas del negocio","Cuando nos traen requerimientos, entregamos","La estrategia no es nuestro trabajo \u2014 somos ejecuci\u00f3n"]},
 path:{en:"Earn a seat at the strategy table. Start bringing ideas.",
       es:"Gana un asiento en la mesa de estrategia. Comienza a traer ideas."}},
{code:"CPTI",name:{en:"The Almost There",es:"El Casi Ah\u00ed"},tagline:{en:"One conversation away from excellence.",es:"A una conversaci\u00f3n de la excelencia."},quadrant:"Consolidated",
 description:{en:"Consolidated, proactive, integrated. The only gap: business isn't driving priorities.",
              es:"Consolidado, proactivo, integrado. La \u00fanica brecha: el negocio no impulsa las prioridades."},
 strengths:{en:["Strong execution","Technical excellence","Integrated workflows"],
            es:["Ejecuci\u00f3n fuerte","Excelencia t\u00e9cnica","Flujos de trabajo integrados"]},
 blindspots:{en:["Tech \u2260 business priorities","Technical metrics only","Business sees A.I. as IT's"],
             es:["Tech \u2260 prioridades del negocio","Solo m\u00e9tricas t\u00e9cnicas","El negocio ve la I.A. como de IT"]},
 symptoms:{en:["Our A.I. is great \u2014 we just need better business engagement","We measure model accuracy, not business impact","Business should be more involved, but they're not interested"],
           es:["Nuestra I.A. es genial \u2014 solo necesitamos mejor compromiso del negocio","Medimos precisi\u00f3n del modelo, no impacto en el negocio","El negocio deber\u00eda estar m\u00e1s involucrado, pero no les interesa"]},
 path:{en:"Connect one A.I. initiative to a metric the CEO cares about.",
       es:"Conecta una iniciativa de I.A. a una m\u00e9trica que le importe al CEO."}},
{code:"CPBI",name:{en:"The Strategic Leader",es:"El L\u00edder Estrat\u00e9gico"},tagline:{en:"A.I. is how we compete.",es:"La I.A. es c\u00f3mo competimos."},quadrant:"Consolidated",
 description:{en:"You've cracked the code. Consolidated tools, proactive roadmap, business drives priorities, A.I. embedded in workflows.",
              es:"Has descifrado el c\u00f3digo. Herramientas consolidadas, roadmap proactivo, el negocio impulsa las prioridades, I.A. integrada en los flujos de trabajo."},
 strengths:{en:["Clear ROI metrics","High adoption rates","Executive alignment","Competitive advantage"],
            es:["M\u00e9tricas de ROI claras","Altas tasas de adopci\u00f3n","Alineaci\u00f3n ejecutiva","Ventaja competitiva"]},
 blindspots:{en:["Risk of complacency","May over-engineer","Talent retention critical"],
             es:["Riesgo de complacencia","Puede sobre-ingenier\u00eda","Retenci\u00f3n de talento cr\u00edtica"]},
 symptoms:{en:["Our A.I. initiatives delivered $2M in efficiency gains last quarter","Every department has an A.I. roadmap aligned to business goals","We killed three tools last month because they weren't performing"],
           es:["Nuestras iniciativas de I.A. entregaron $2M en ganancias de eficiencia el \u00faltimo trimestre","Cada departamento tiene un roadmap de I.A. alineado a los objetivos del negocio","Eliminamos tres herramientas el mes pasado porque no rend\u00edan"]},
 path:{en:"Focus on talent, stay paranoid about disruption, consider how A.I. reshapes your business model.",
       es:"Enf\u00f3cate en el talento, mantente paranoico sobre la disrupci\u00f3n, considera c\u00f3mo la I.A. transforma tu modelo de negocio."}},
];

// Tier ranking for sorting (CPBI > C* > S*)
const TIER_RANK = {
  CPBI: 1, CPBE: 2, CPTI: 2, SPBI: 2,
  CPTB: 3, CPTE: 3, CRBI: 3, CRTI: 3, SPTB: 3, SPTI: 3, SPTE: 3,
  CRTB: 4, CRTE: 4, SRBI: 4, SRTB: 4, SRTE: 4, SRTI: 4,
};

// Mapping from type code to which dimension letters it satisfies (for badges)
function dimsFor(code) {
  const d = [];
  if (code[0] === 'C') d.push('S');             // Consolidated
  if (code[1] === 'P') d.push('O');             // Proactive
  if (code[2] === 'B') d.push('L');             // Business-driven
  if (code[3] === 'I') d.push('I');             // Integrated
  return d;
}

const t = (k, lang) => (k && k[lang]) || (k && k.en) || '';

Object.assign(window, { I18N, DIMENSIONS, TYPES, TIER_RANK, dimsFor, t });
